local ui2 = require('vim._core.ui2')
ui2.enable({enable = true, msg = {target = 'msg'}})
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'msg',
  callback = function ()
    vim._with({win = ui2.wins.msg}, function ()
      vim.opt_local.winhl:append('Normal:Comment')
    end)
  end
})

require('arctgx.lazy')
require('arctgx.start.00-vimsettings')
require('arctgx.start.01-basicMappings')
require('arctgx.start.02-abstractKeymaps')
-- override lsp functions before setup lspconfig
require('arctgx.start.lsp')
require('arctgx.start.03-configuration')
require('arctgx.start.cmdlineIgnoreCase')
require('arctgx.start.colorscheme')
require('arctgx.start.diagnostic-config')
require('arctgx.start.insertHlsToggle')
require('arctgx.start.opener')
require('arctgx.start.restore-last-position')
require('arctgx.start.server')
require('arctgx.start.session')
require('arctgx.start.shell')
require('arctgx.start.filetypes')
require('arctgx.treesitter').loadOnFiletype()
require('arctgx.completion').init()
