local keymap = require('arctgx.vim.abstractKeymap')
vim.g.arctgxBackupDir = vim.fs.joinpath(vim.env['XDG_CONFIG_HOME'] or os.getenv('HOME'), '.config', 'backups')
keymap.set('n', 'writeBackup', function ()
  require('arctgx.writebackup').save()
end)
