local keymap = require('arctgx.vim.abstractKeymap')

keymap.set({'n'}, 'langIncrementSelection', function ()
  require('nvim-treesitter-selection.incremental_selection').init_selection()
end)
keymap.set({'x'}, 'langIncrementSelection', function ()
  require('nvim-treesitter-selection.incremental_selection').node_incremental()
end)
keymap.set({'x'}, 'langDecrementSelection', function ()
  require('nvim-treesitter-selection.incremental_selection').node_decremental()
end)
